name: check-pr
on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]
concurrency:
  group: check-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true
permissions:
  contents: read
  pull-requests: read
jobs:
  verify:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        timeout-minutes: 5
        with:
          ref: ${{ github.sha }}
          persist-credentials: false
      - uses: ./
        timeout-minutes: 5
        with:
          command: pr
          argument: ${{ github.event.pull_request.number }}
          format: json
          policy: oss
          audit: "true"
